# Generated by Django 4.2.1 on 2023-05-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='post_media/%y/%m/%d/', verbose_name='media')),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='post')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='posted')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('in_response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.post')),
                ('media', models.ManyToManyField(to='blogApp.media')),
            ],
        ),
    ]
